name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.MY_PAT }}
    - name: Build the Docker image
      env:
       MY_PAT: ${{ secrets.MY_PAT }}
      run: ./run.sh
    - name: Scan image
      uses: anchore/scan-action@v2
      with:
         image: ghcr.io/notopss/copenhagen:${{ BUILD_NUMBER }}
